(deftheme wheatgrass-hybrid
  "Created by Andy Tan at 2017-07-16. Wheatgrass-hybrid is a modified version
of wheatgrass theme that comes with native version of Emacs and blackboard-theme.el.")

(custom-theme-set-faces
 'wheatgrass-hybrid
 '(default ((t(:foreground "wheat" :background "#0C1021"))))
 `(bold ((t (:bold t))))
 `(bold-italic ((t (:bold t))))
 `(border-glyph ((t (nil))))
 `(buffers-tab ((t (:background "#0C1021" :foreground "#F8F8F8"))))
 '(cursor ((t (:background "thistle"))))
 '(error ((t (:foreground "salmon1"))))
 '(warning ((t (:foreground "orange"))))
 '(success ((t (:foreground "yellow green"))))
 '(highlight ((t (:foreground "white" :background "brown"))))
 '(region ((t (:inherit nil :foreground nil :background "#8b0a50"))))
 '(hl-line ((t (:foreground nil :background "#2b3354"))))
 '(secondary-selection ((t (:background "dark slate gray"))))
 '(isearch ((t (:foreground "white" :background "dark goldenrod"))))
 '(lazy-highlight ((t (:background "gray25"))))
 '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
 '(font-lock-comment-face ((t (:foreground "SpringGreen3"))))
 '(font-lock-constant-face ((t (:foreground "turquoise"))))
 '(font-lock-function-name-face ((t (:foreground "pale green"))))
 '(font-lock-keyword-face ((t (:foreground "dark orange"))))
 '(font-lock-string-face ((t (:foreground "dark khaki"))))
 '(font-lock-type-face ((t (:foreground "aquamarine"))))
 '(font-lock-variable-name-face ((t (:foreground "yellow green"))))
 '(link ((t (:underline t :foreground "cyan"))))
 '(link-visited ((t (:underline t :foreground "dark cyan"))))

;; org-mode
`(org-hide ((t (:foreground "#2e3436"))))
`(org-level-1 ((t (:bold nil :foreground "dodger blue" :height 1.3))))
`(org-level-2 ((t (:bold nil :foreground "#edd400" :height 1.2))))
`(org-level-3 ((t (:bold nil :foreground "#6ac214" :height 1.1))))
`(org-level-4 ((t (:bold nil :foreground "tomato" :height 1.0))))
`(org-date ((t (:underline t :foreground "magenta3"))))
`(org-footnote  ((t (:underline t :foreground "magenta3"))))
`(org-link ((t (:foreground "skyblue2" :background "#2e3436"))))
`(org-special-keyword ((t (:foreground "brown"))))
`(org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
`(org-block ((t (:foreground "#bbbbbc"))))
`(org-quote ((t (:inherit org-block :slant italic))))
`(org-verse ((t (:inherit org-block :slant italic))))
`(org-todo ((t (:bold t :foreground "Red"))))
`(org-done ((t (:bold t :foreground "ForestGreen"))))
`(org-agenda-structure ((t (:weight bold :foreground "tomato"))))
`(org-agenda-date ((t (:foreground "#6ac214"))))
`(org-agenda-date-weekend ((t (:weight normal :foreground "dodger blue"))))
`(org-agenda-date-today ((t (:weight bold :foreground "#edd400"))))

`(font-lock-string-face ((t (:foreground "#61CE3C"))))
`(font-lock-type-face ((t (:foreground "#8DA6CE"))))
`(font-lock-variable-name-face ((t (:foreground "#FF6400"))))
`(font-lock-warning-face ((t (:bold t :foreground "pink"))))
`(gui-element ((t (:background "#D4D0C8" :foreground "black"))))
`(region ((t (:foreground nil :background "#253B76"))))
`(mode-line ((t (:background "grey75" :foreground "black"))))
`(highlight ((t (:background "#222222"))))
`(highline-face ((t (:background "SeaGreen"))))
`(italic ((t (nil))))
`(left-margin ((t (nil))))
`(text-cursor ((t (:background "yellow" :foreground "black"))))
`(toolbar ((t (nil))))
`(underline ((nil (:underline nil))))
`(zmacs-region ((t (:background "snow" :foreground "ble")))))

(provide-theme 'wheatgrass-hybrid)

;; wheatgrass-hybrid-theme.el ends here.
